on:
  [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Install Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.x
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install
    - run: npm run pretest
    - run: export DISPLAY=99.0
      if: runner.os == 'Linux'
    - run: sudo apt update
      if: runner.os == 'Linux'
    - run: sudo apt install -y libasound2 libgbm1 libgtk-3-0 libnss3 xvfb
      if: runner.os == 'Linux'
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'

